# Generated by Django 5.2.3 on 2025-08-11 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_base', '0001_initial'),
        ('llm', '0001_initial'),
        ('user', '0012_teaminvitation_invitation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='embedding_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_bases', to='llm.embeddingmodel', verbose_name='embedding model'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='embedding_provider_config',
            field=models.ForeignKey(blank=True, help_text='Provider configuration for embedding models', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embedding_knowledge_bases', to='llm.providerconfig', verbose_name='embedding provider config'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='summarization_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summarization_knowledge_bases', to='llm.llmmodel', verbose_name='summarization model'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='summarization_provider_config',
            field=models.ForeignKey(blank=True, help_text='Provider configuration for summarization models', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summarization_knowledge_bases', to='llm.providerconfig', verbose_name='summarization provider config'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to='user.team', verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='knowledgebasedocument',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledge_base.knowledgebase', verbose_name='Knowledge Base'),
        ),
        migrations.AddField(
            model_name='knowledgebasechunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge_base.knowledgebasedocument', verbose_name='Document'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgebasedocument',
            unique_together={('knowledge_base', 'source_type', 'source')},
        ),
    ]
