# Generated by Django 5.2.9 on 2025-12-24 22:28

import django.db.models.deletion
import knowledge_base.utils
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_initial'),
        ('llm', '0002_alter_providerconfig_api_key'),
    ]

    operations = [
        migrations.RunSQL(
            # activate pgvector extension
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;",
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='embedding_model',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='summarization_model',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='summarizer_temperature',
        ),
        migrations.RemoveField(
            model_name='knowledgebasechunk',
            name='keywords',
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='embedding_model_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Embedding Model'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='summarization_model_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Summarization Model'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='summarizer_llm_config',
            field=models.JSONField(blank=True, default=dict, help_text='LLM config to be provided to the summarizer', null=True, verbose_name='Summarizer LLM Config'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='vector_store_type',
            field=models.CharField(default='postgres', help_text='Type of vector store used for this knowledge base', max_length=50, verbose_name='Vector Store Type'),
        ),
        migrations.AddField(
            model_name='knowledgebasechunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, help_text='Vector embedding for semantic search', null=True, verbose_name='Embedding'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='chunk_seperator',
            field=models.JSONField(default=knowledge_base.utils.chunk_default_separators, help_text='Separator used to split documents into chunks', verbose_name='Chunk separator'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='embedding_provider_config',
            field=models.ForeignKey(blank=True, help_text='Provider configuration for embedding models', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embedding_knowledge_bases', to='llm.providerconfig', verbose_name='Embedding Provider Config'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='summarization_provider_config',
            field=models.ForeignKey(blank=True, help_text='Provider configuration for summarization models', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summarization_knowledge_bases', to='llm.providerconfig', verbose_name='Summarization Provider Config'),
        ),
        migrations.CreateModel(
            name='RetrievalSetting',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name for this retrieval setting', max_length=255, verbose_name='Name')),
                ('retrieval_type', models.CharField(choices=[('vector_search', 'Vector Search'), ('full_text_search', 'Full-Text Search'), ('hybrid_search', 'Hybrid Search')], default='hybrid_search', help_text='Type of retrieval to use', max_length=50, verbose_name='Retrieval Type')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default retrieval setting for the knowledge base', verbose_name='Is Default')),
                ('reranker_enabled', models.BooleanField(default=False, help_text='Whether to use reranker model for post-processing results', verbose_name='Reranker Enabled')),
                ('reranker_model_key', models.CharField(blank=True, help_text='Model key for reranker (required if reranker_enabled is true)', max_length=255, null=True, verbose_name='Reranker Model Key')),
                ('top_k', models.PositiveIntegerField(default=3, help_text='Number of top results to retrieve', verbose_name='Top K')),
                ('hybrid_alpha', models.FloatField(blank=True, default=0.7, help_text='Weight for semantic search in hybrid mode (0.0-1.0, higher = more semantic). Used for weighted score ranking when reranker_enabled is false.', null=True, verbose_name='Hybrid Alpha')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_settings', to='knowledge_base.knowledgebase', verbose_name='Knowledge Base')),
                ('reranker_provider_config', models.ForeignKey(blank=True, help_text='Provider configuration for reranker model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reranker_retrieval_settings', to='llm.providerconfig', verbose_name='Reranker Provider Config')),
            ],
            options={
                'verbose_name': 'Retrieval Setting',
                'verbose_name_plural': 'Retrieval Settings',
                'unique_together': {('knowledge_base', 'name')},
            },
        ),
    ]
