# Generated by Django 5.2.3 on 2025-08-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebasedocument',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reindexing', 'Reindexing'), ('crawling', 'Crawling'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='new', max_length=20, verbose_name='Status'),
        ),
    ]
