# Generated by Django 5.2.3 on 2025-08-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0003_alter_knowledgebasedocument_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='summarizer_temperature',
            field=models.FloatField(blank=True, default=0.7, help_text='Temperature to be provided to the summarizer', null=True, verbose_name='Summarizer Temperature'),
        ),
    ]
