# Generated by Django 5.2.11 on 2026-02-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0003_remove_knowledgebase_embedding_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrievalsetting',
            name='reranker_model_config',
            field=models.JSONField(blank=True, default=dict, help_text='Model config to be provided to the reranker', null=True, verbose_name='Reranker Model Config'),
        ),
        migrations.AddField(
            model_name='retrievalsetting',
            name='retrieval_cost',
            field=models.PositiveIntegerField(default=0, help_text='The cost in credits per retrieval using this setting', verbose_name='Retrieval Cost'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='vector_store_type',
            field=models.CharField(default='opensearch', help_text='Type of vector store used for this knowledge base', max_length=50, verbose_name='Vector Store Type'),
        ),
    ]
