# Generated by Django 5.2.11 on 2026-02-23 11:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0004_retrievalsetting_reranker_model_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseQuery',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query_text', models.TextField(help_text='The search query submitted by the user', verbose_name='Query Text')),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('finished', 'Finished'), ('failed', 'Failed')], default='new', max_length=20, verbose_name='Status')),
                ('results_count', models.PositiveIntegerField(default=0, help_text='Number of results returned', verbose_name='Results Count')),
                ('retrieval_cost', models.PositiveIntegerField(default=0, help_text='The cost in credits for this query', verbose_name='Retrieval Cost')),
                ('error_message', models.TextField(blank=True, help_text='Error message if query failed', null=True, verbose_name='Error Message')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='knowledge_base.knowledgebase', verbose_name='Knowledge Base')),
                ('retrieval_setting', models.ForeignKey(blank=True, help_text='The retrieval setting used for this query', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='knowledge_base.retrievalsetting', verbose_name='Retrieval Setting')),
            ],
            options={
                'verbose_name': 'Knowledge Base Query',
                'verbose_name_plural': 'Knowledge Base Queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
