# Generated by Django 5.1.4 on 2025-01-13 22:16

import core.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlResultAttachment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment_type', models.CharField(choices=[('pdf', 'PDF'), ('screenshot', 'Screenshot')], max_length=255, verbose_name='attachment type')),
                ('attachment', models.FileField(upload_to=core.utils.generate_crawl_result_attachment_path, verbose_name='attachment')),
                ('crawl_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.crawlresult')),
            ],
            options={
                'verbose_name': 'Crawl Result Attachment',
                'verbose_name_plural': 'Crawl Result Attachments',
            },
        ),
    ]
