# Generated by Django 5.1.4 on 2025-01-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_crawlrequest_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlresult',
            name='url',
            field=models.URLField(max_length=2048, verbose_name='url'),
        ),
    ]
