from django.utils.translation import gettext_lazy as _

PLAN_GROUP_YEARLY = 'yearly'
PLAN_GROUP_MONTHLY = 'monthly'

PLAN_GROUP_CHOICES = (
    (PLAN_GROUP_YEARLY, _('Yearly')),
    (PLAN_GROUP_MONTHLY, _('Monthly')),
)

STRIPE_SUBSCRIPTION_STATUS_ACTIVE = 'active'
STRIPE_SUBSCRIPTION_STATUS_CANCELED = 'canceled'
STRIPE_SUBSCRIPTION_STATUS_INCOMPLETE = 'incomplete'
STRIPE_SUBSCRIPTION_STATUS_INCOMPLETE_EXPIRED = 'incomplete_expired'
STRIPE_SUBSCRIPTION_STATUS_PAST_DUE = 'past_due'
STRIPE_SUBSCRIPTION_STATUS_PAUSED = 'paused'
STRIPE_SUBSCRIPTION_STATUS_TRIALING = 'trialing'
STRIPE_SUBSCRIPTION_STATUS_UNPAID = 'unpaid'

STRIPE_SUBSCRIPTION_STATUS_CHOICES = (
    (STRIPE_SUBSCRIPTION_STATUS_ACTIVE, _('Active')),
    (STRIPE_SUBSCRIPTION_STATUS_CANCELED, _('Canceled')),
    (STRIPE_SUBSCRIPTION_STATUS_INCOMPLETE, _('Incomplete')),
    (STRIPE_SUBSCRIPTION_STATUS_INCOMPLETE_EXPIRED, _('Incomplete Expired')),
    (STRIPE_SUBSCRIPTION_STATUS_PAST_DUE, _('Past Due')),
    (STRIPE_SUBSCRIPTION_STATUS_PAUSED, _('Paused')),
    (STRIPE_SUBSCRIPTION_STATUS_TRIALING, _('Trialing')),
    (STRIPE_SUBSCRIPTION_STATUS_UNPAID, _('Unpaid')),
)

PLAN_FEATURE_ICON_INFO = 'info'
PLAN_FEATURE_ICON_CROSS = 'cross'
PLAN_FEATURE_ICON_CHECK = 'check'
PLAN_FEATURE_ICON_CHOICES = (
    ('', _('Default')),
    (PLAN_FEATURE_ICON_INFO, _('Info')),
    (PLAN_FEATURE_ICON_CROSS, _('Cross')),
    (PLAN_FEATURE_ICON_CHECK, _('Check')),
)
