# Generated by Django 5.1.4 on 2024-12-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='reset password expires at'),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='reset password token'),
        ),
    ]
