# Generated by Django 5.1.4 on 2025-01-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_team_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamapikey',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last used at'),
        ),
    ]
