# Generated by Django 5.1.4 on 2025-02-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_teamapikey_last_used_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='stripe customer id'),
        ),
    ]
