# Generated by Django 5.1.8 on 2025-04-06 13:02

import user.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_newsletter_confirmed_user_privacy_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvitation',
            name='invitation_token',
            field=models.CharField(default=user.utils.generate_random_invitation_code, max_length=255, null=True, verbose_name='invitation token'),
        ),
    ]
