# Generated by Django 5.2.8 on 2025-11-18 23:30

import django.db.models.deletion
import user.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_teaminvitation_invitation_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='teamapikey',
            options={'verbose_name': 'Team API Key', 'verbose_name_plural': 'Team API Keys'},
        ),
        migrations.AlterModelOptions(
            name='teaminvitation',
            options={'verbose_name': 'Team Invitation', 'verbose_name_plural': 'Team Invitations'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='team',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Is Default'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', through='user.TeamMember', to=settings.AUTH_USER_MODEL, verbose_name='Members'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Customer ID'),
        ),
        migrations.AlterField(
            model_name='teamapikey',
            name='key',
            field=models.CharField(default=user.utils.generate_random_api_key, max_length=255, unique=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='teamapikey',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Used At'),
        ),
        migrations.AlterField(
            model_name='teamapikey',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='teamapikey',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='user.team', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='activated',
            field=models.BooleanField(default=False, verbose_name='Activated'),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='invitation_token',
            field=models.CharField(default=user.utils.generate_random_invitation_code, max_length=255, null=True, verbose_name='Invitation Token'),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='user.team', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='Is Owner'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='user.team', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_teams', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email Verification Token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email Verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='newsletter_confirmed',
            field=models.BooleanField(default=False, verbose_name='Newsletter Confirmed'),
        ),
        migrations.AlterField(
            model_name='user',
            name='privacy_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Privacy Confirmed At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reset_password_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reset Password Expires At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reset Password Token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='terms_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terms Confirmed At'),
        ),
    ]
