# Generated by Django 5.2.9 on 2025-12-16 23:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user', '0013_alter_team_options_alter_teamapikey_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(help_text="MIME type of the file (e.g., 'text/csv', 'application/json')", max_length=255, verbose_name='Content Type')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('file', models.FileField(upload_to='media/%Y/%m/%d/', verbose_name='File')),
                ('size', models.PositiveIntegerField(help_text='File size in bytes', verbose_name='Size')),
                ('related_object_id', models.UUIDField(blank=True, null=True, verbose_name='Related Object ID')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (e.g., conversation_id, agent_version_id)', verbose_name='Metadata')),
                ('related_object_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='contenttypes.contenttype', verbose_name='Related Object Type')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='user.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['team', '-created_at'], name='user_media_team_id_32e262_idx'), models.Index(fields=['related_object_type', 'related_object_id'], name='user_media_related_428b9b_idx')],
            },
        ),
    ]
