# Generated by Django 5.1.8 on 2025-04-27 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_searchrequest'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagehistory',
            name='search_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='usage_history', to='core.searchrequest', verbose_name='Search request'),
        ),
        migrations.AlterField(
            model_name='usagehistory',
            name='crawl_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='usage_history', to='core.crawlrequest', verbose_name='Crawl request'),
        ),
    ]
