# Generated by Django 5.2.3 on 2025-06-25 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_crawlrequest_crawl_type'),
        ('plan', '0002_usagehistory_search_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagehistory',
            name='sitemap_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='usage_history', to='core.sitemaprequest', verbose_name='Sitemap request'),
        ),
    ]
