# Generated by Django 5.2.3 on 2025-08-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_usagehistory_sitemap_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='number_of_each_knowledge_base_documents',
            field=models.IntegerField(default=100, verbose_name='Number of each knowledge base documents'),
        ),
        migrations.AddField(
            model_name='plan',
            name='number_of_knowledge_bases',
            field=models.IntegerField(default=1, verbose_name='Number of knowledge bases'),
        ),
    ]
