# Generated by Django 5.2.3 on 2025-08-07 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('plan', '0004_plan_number_of_each_knowledge_base_documents_and_more'),
        ('user', '0012_teaminvitation_invitation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagehistory',
            name='content_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Content id'),
        ),
        migrations.AddField(
            model_name='usagehistory',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='usage_histories', to='contenttypes.contenttype', verbose_name='Content type'),
        ),
        migrations.AddField(
            model_name='usagehistory',
            name='team_api_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_histories', to='user.teamapikey', verbose_name='API key'),
        )
    ]
