# Generated by Django 5.2.3 on 2025-08-07 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_auto_20250807_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usagehistory',
            name='crawl_request',
        ),
        migrations.RemoveField(
            model_name='usagehistory',
            name='search_request',
        ),
        migrations.RemoveField(
            model_name='usagehistory',
            name='sitemap_request',
        ),
    ]
