# Generated by Django 5.2.3 on 2025-08-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_remove_usagehistory_crawl_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='knowledge_base_retrival_rate_limit',
            field=models.CharField(blank=True, default=None, help_text="DRF-style rate string, e.g. '100/min', '500/day'", max_length=100, null=True, verbose_name='Knowledge base retrival rate limit'),
        ),
    ]
