# Generated by Django 5.2.8 on 2025-11-21 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_plan_knowledge_base_retrival_rate_limit'),
        ('user', '0013_alter_team_options_alter_teamapikey_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='plan.subscription', verbose_name='Subscription'),
        ),
        migrations.AlterField(
            model_name='usagehistory',
            name='content_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Content ID'),
        ),
        migrations.AlterField(
            model_name='usagehistory',
            name='requested_page_credit',
            field=models.PositiveIntegerField(verbose_name='Requested Page Credit'),
        ),
        migrations.AlterField(
            model_name='usagehistory',
            name='team_api_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_histories', to='user.teamapikey', verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='usagehistory',
            name='used_page_credit',
            field=models.PositiveIntegerField(verbose_name='Actual Page Credit Used'),
        ),
    ]
