# Generated by Django 5.2.9 on 2025-12-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_alter_subscriptionpayment_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='agent_rate_limit',
            field=models.CharField(blank=True, default=None, help_text="DRF-style rate string, e.g. '100/min', '500/day'", max_length=100, null=True, verbose_name='Agent call rate limit'),
        ),
        migrations.AddField(
            model_name='plan',
            name='number_of_agents',
            field=models.IntegerField(default=1, verbose_name='Number of agents'),
        ),
    ]
