# Generated by Django 5.2.9 on 2025-12-24 22:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_base', '0002_initial'),
        ('llm', '0002_alter_providerconfig_api_key'),
        ('user', '0014_add_media_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='LLM Description')),
                ('key', models.CharField(max_length=255, verbose_name='Key')),
                ('tool_type', models.CharField(choices=[('api_spec', 'API Specification'), ('built_in', 'Built-in'), ('mcp', 'MCP')], max_length=255, verbose_name='Tool Type')),
                ('input_schema', models.JSONField(blank=True, default=None, null=True)),
                ('output_schema', models.JSONField(blank=True, default=None, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='user.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='user.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
        ),
        migrations.CreateModel(
            name='AgentVersion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', verbose_name='Status')),
                ('system_prompt', models.TextField(blank=True, null=True, verbose_name='System Prompt')),
                ('llm_model_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='LLM Model')),
                ('llm_configs', models.JSONField(default=dict)),
                ('json_output', models.BooleanField(default=False, help_text='Enable structured JSON output formatting', verbose_name='JSON Output')),
                ('json_schema', models.JSONField(blank=True, help_text='JSON Schema for structured output format', null=True, verbose_name='JSON Schema')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='agent.agent', verbose_name='Agent')),
                ('provider_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='llm.providerconfig', verbose_name='Config Provider')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
        ),
        migrations.CreateModel(
            name='APISpec',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('api_spec', models.JSONField(default=dict)),
                ('base_url', models.URLField()),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_specs', to='user.team', verbose_name='Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='APISpecParameters',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool_parameter_type', models.CharField(choices=[('header', 'Header'), ('query', 'Query'), ('oauth', 'OAuth')], max_length=255, verbose_name='Tool Parameter Type')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('value', models.TextField(verbose_name='Value')),
                ('api_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='agent.apispec', verbose_name='API Spec')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContextParameters',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter_type', models.CharField(choices=[('string', 'String'), ('boolean', 'Boolean'), ('number', 'Number')], max_length=255, verbose_name='Parameter Type')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('value', models.TextField(blank=True, default=None, null=True, verbose_name='Value')),
                ('agent_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='agent.agentversion', verbose_name='Agent Version')),
            ],
            options={
                'verbose_name': 'Agent Context Parameter',
                'verbose_name_plural': 'Agent Context Parameters',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('user_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='agent.agent', verbose_name='agent')),
                ('agent_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='agent.agentversion', verbose_name='agent version')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='user.team', verbose_name='team')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
            },
        ),
        migrations.CreateModel(
            name='MCPServer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('url', models.URLField(verbose_name='URL')),
                ('transport_type', models.CharField(choices=[('sse', 'SSE'), ('streamable_http', 'Streamable HTTP')], default=None, max_length=50, null=True, verbose_name='Transport Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('error', 'Error'), ('oauth_required', 'OAuth Authentication Required'), ('auth_required', 'Authentication Required')], default='pending', max_length=50, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcp_servers', to='user.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'MCP Server',
                'verbose_name_plural': 'MCP Servers',
            },
        ),
        migrations.CreateModel(
            name='MCPServerParameters',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool_parameter_type', models.CharField(choices=[('header', 'Header'), ('query', 'Query'), ('oauth', 'OAuth')], max_length=255, verbose_name='Tool Parameter Type')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('value', models.TextField(verbose_name='Value')),
                ('mcp_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='agent.mcpserver', verbose_name='MCP Server')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageBlock',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='agent.conversation', verbose_name='conversation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('message_type', models.CharField(max_length=20)),
                ('content', models.JSONField()),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('tool_call_id', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_kwargs', models.JSONField(blank=True, default=dict)),
                ('response_metadata', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent.conversation')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent.messageblock')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentKnowledgeBase',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.JSONField(default=dict)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_knowledge_bases', to='knowledge_base.knowledgebase', verbose_name='Knowledge Base')),
                ('agent_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_knowledge_bases', to='agent.agentversion', verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'Agent Knowledge Base',
                'verbose_name_plural': 'Agent Knowledge Bases',
                'unique_together': {('agent_version', 'knowledge_base')},
            },
        ),
        migrations.CreateModel(
            name='AgentAsTool',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.JSONField(default=dict, help_text='Configuration for how the tool agent should be invoked')),
                ('tool_agent', models.ForeignKey(help_text='The agent to be used as a tool', on_delete=django.db.models.deletion.CASCADE, related_name='used_as_tool_in', to='agent.agent', verbose_name='Tool Agent')),
                ('parent_agent_version', models.ForeignKey(help_text='The agent version that uses this agent as a tool', on_delete=django.db.models.deletion.CASCADE, related_name='agent_as_tools', to='agent.agentversion', verbose_name='Parent Agent Version')),
            ],
            options={
                'verbose_name': 'Agent as Tool',
                'verbose_name_plural': 'Agents as Tools',
                'unique_together': {('parent_agent_version', 'tool_agent')},
            },
        ),
        migrations.CreateModel(
            name='APISpecTool',
            fields=[
                ('tool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agent.tool')),
                ('method', models.CharField(max_length=255, verbose_name='Method')),
                ('path', models.CharField(max_length=255, verbose_name='Path')),
                ('content_type', models.CharField(default='application/json', max_length=255, verbose_name='Content Type')),
                ('api_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='agent.apispec', verbose_name='API Spec')),
            ],
            options={
                'verbose_name': 'API Spec Tool',
                'verbose_name_plural': 'API Spec Tools',
            },
            bases=('agent.tool',),
        ),
        migrations.CreateModel(
            name='MCPTool',
            fields=[
                ('tool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agent.tool')),
                ('mcp_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='agent.mcpserver', verbose_name='MCP Server')),
            ],
            options={
                'verbose_name': 'MCP Tool',
                'verbose_name_plural': 'MCP Tools',
            },
            bases=('agent.tool',),
        ),
        migrations.CreateModel(
            name='AgentTool',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.JSONField()),
                ('agent_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tools', to='agent.agentversion', verbose_name='Agent')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tools', to='agent.tool', verbose_name='Tool')),
            ],
            options={
                'verbose_name': 'Agent Tool',
                'verbose_name_plural': 'Agent Tools',
                'unique_together': {('agent_version', 'tool')},
            },
        ),
    ]
