# Generated by Django 5.2.9 on 2026-01-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageblock',
            name='structured_response',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
