# Generated by Django 5.2.11 on 2026-02-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_messageblock_structured_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apispecparameters',
            name='tool_parameter_type',
            field=models.CharField(choices=[('path', 'Path'), ('header', 'Header'), ('query', 'Query'), ('oauth', 'OAuth')], max_length=255, verbose_name='Tool Parameter Type'),
        ),
        migrations.AlterField(
            model_name='mcpserver',
            name='transport_type',
            field=models.CharField(choices=[('sse', 'SSE'), ('streamable_http', 'Streamable HTTP')], default='streamable_http', max_length=50, null=True, verbose_name='Transport Type'),
        ),
        migrations.AlterField(
            model_name='mcpserverparameters',
            name='tool_parameter_type',
            field=models.CharField(choices=[('path', 'Path'), ('header', 'Header'), ('query', 'Query'), ('oauth', 'OAuth')], max_length=255, verbose_name='Tool Parameter Type'),
        ),
    ]
