# Generated by Django 5.2.11 on 2026-02-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_alter_apispecparameters_tool_parameter_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='enable_as_tool',
            field=models.BooleanField(default=False, help_text='Allow this agent to be used as a tool in other agents', verbose_name='Enable as Tool'),
        ),
        migrations.AddField(
            model_name='agent',
            name='tool_description',
            field=models.TextField(blank=True, help_text='Description of what this agent does when used as a tool', null=True, verbose_name='Tool Description'),
        ),
        migrations.AddField(
            model_name='agent',
            name='tool_function_name',
            field=models.CharField(blank=True, help_text='Custom function name when used as a tool', max_length=255, null=True, verbose_name='Tool Function Name'),
        ),
    ]
