# Generated by Django 5.2.3 on 2025-08-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerconfig',
            name='api_key',
            field=models.TextField(verbose_name='API Key'),
        ),
    ]
