# Generated by Django 5.2.3 on 2025-08-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='default_temperature',
            field=models.FloatField(blank=True, default=0.7, null=True, verbose_name='Default Temperature'),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='max_temperature',
            field=models.FloatField(blank=True, default=2.0, null=True, verbose_name='Max Temperature'),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='min_temperature',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Min Temperature'),
        ),
        migrations.AlterField(
            model_name='embeddingmodel',
            name='provider_name',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('watercrawl', 'WaterCrawl')], default='openai', max_length=255, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='provider_name',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('watercrawl', 'WaterCrawl')], default='openai', max_length=255, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='providerconfig',
            name='provider_name',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('watercrawl', 'WaterCrawl')], default='openai', max_length=255, verbose_name='Provider'),
        ),
    ]
