# Generated by Django 5.2.9 on 2025-12-24 22:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0003_remove_knowledgebase_embedding_model_and_more'),
        ('llm', '0002_alter_providerconfig_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConfigModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_key', models.CharField(help_text='Unique identifier for the model', max_length=255, verbose_name='Model Key')),
                ('model_type', models.CharField(choices=[('llm', 'LLM'), ('embedding', 'Embedding'), ('reranker', 'Reranker')], default='llm', max_length=50, verbose_name='Model Type')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this model is available for use', verbose_name='Is Active')),
                ('is_custom', models.BooleanField(default=False, help_text='Whether this is a custom user-defined model', verbose_name='Is Custom')),
                ('custom_label', models.CharField(blank=True, help_text='Human-readable label for custom models', max_length=255, null=True, verbose_name='Custom Label')),
                ('custom_config', models.JSONField(blank=True, default=dict, help_text='Custom model configuration (features, model_properties, parameter_rules)', verbose_name='Custom Configuration')),
            ],
            options={
                'verbose_name': 'Provider Config Model',
                'verbose_name_plural': 'Provider Config Models',
                'ordering': ['model_type', 'model_key'],
            },
        ),
        migrations.DeleteModel(
            name='EmbeddingModel',
        ),
        migrations.DeleteModel(
            name='LLMModel',
        ),
        migrations.AlterField(
            model_name='providerconfig',
            name='provider_name',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google-genai', 'Google Generative AI'), ('cohere', 'Cohere'), ('ollama', 'Ollama')], default='openai', max_length=255, verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='providerconfigmodel',
            name='provider_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='llm.providerconfig', verbose_name='Provider Config'),
        ),
        migrations.AlterUniqueTogether(
            name='providerconfigmodel',
            unique_together={('provider_config', 'model_key', 'model_type')},
        ),
    ]
