# Generated by Django 5.1.4 on 2024-12-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_reset_password_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminvitation',
            name='active',
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='activated',
            field=models.BooleanField(default=False, verbose_name='activated'),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='email address'),
        ),
    ]
