# Generated by Django 5.1.4 on 2024-12-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_default',
            field=models.BooleanField(default=True, verbose_name='is default'),
        ),
    ]
