# Generated by Django 5.1.4 on 2025-01-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_team_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='is default'),
        ),
    ]
