# Generated by Django 5.1.4 on 2025-02-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_unique_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newsletter_confirmed',
            field=models.BooleanField(default=False, verbose_name='newsletter confirmed'),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='privacy confirmed at'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='terms confirmed at'),
        ),
    ]
