from django.utils.translation import gettext_lazy as _

DOCUMENT_STATUS_NEW = "new"
DOCUMENT_STATUS_REINDEXING = "reindexing"
DOCUMENT_STATUS_CRAWLING = "crawling"
DOCUMENT_STATUS_PROCESSING = "processing"
DOCUMENT_STATUS_READY = "ready"
DOCUMENT_STATUS_FAILED = "failed"

DOCUMENT_STATUS_CHOICES = (
    (DOCUMENT_STATUS_NEW, _("New")),
    (DOCUMENT_STATUS_REINDEXING, _("Reindexing")),
    (DOCUMENT_STATUS_CRAWLING, _("Crawling")),
    (DOCUMENT_STATUS_PROCESSING, _("Processing")),
    (DOCUMENT_STATUS_READY, _("Ready")),
    (DOCUMENT_STATUS_FAILED, _("Failed")),
)

KNOWLEDGE_BASE_STATUS_ACTIVE = "active"
KNOWLEDGE_BASE_STATUS_ARCHIVED = "archived"
KNOWLEDGE_BASE_STATUS_DELETED = "deleted"
KNOWLEDGE_BASE_STATUS_CHOICES = (
    (KNOWLEDGE_BASE_STATUS_ACTIVE, _("Active")),
    (KNOWLEDGE_BASE_STATUS_ARCHIVED, _("Archived")),
    (KNOWLEDGE_BASE_STATUS_DELETED, _("Deleted")),
)

SUMMARIZER_TYPE_STANDARD = "standard"
SUMMARIZER_TYPE_CONTEXT_AWARE = "context_aware"

SUMMARIZER_TYPE_CHOICES = (
    (SUMMARIZER_TYPE_STANDARD, _("Standard")),
    (SUMMARIZER_TYPE_CONTEXT_AWARE, _("Context-Aware")),
)

DOCUMENT_SOURCE_TYPE_MANUAL = "manual"
DOCUMENT_SOURCE_TYPE_CRAWL = "crawl"
DOCUMENT_SOURCE_TYPE_FILE = "file"
DOCUMENT_SOURCE_TYPE_CHOICES = (
    (DOCUMENT_SOURCE_TYPE_MANUAL, _("Manual")),
    (DOCUMENT_SOURCE_TYPE_FILE, _("File")),
    (DOCUMENT_SOURCE_TYPE_CRAWL, _("Crawl")),
)

VECTOR_STORE_OPENSEARCH = "opensearch"
VECTOR_STORE_POSTGRES = "postgres"
VECTOR_STORE_WEAVIATE = "weaviate"
VECTOR_STORE_CHOICES = (
    (VECTOR_STORE_OPENSEARCH, _("OpenSearch")),
    (VECTOR_STORE_POSTGRES, _("PostgreSQL")),
    (VECTOR_STORE_WEAVIATE, _("Weaviate")),
)
