# Generated by Django 5.1.4 on 2024-12-15 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrequest',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_requests', to='user.team', verbose_name='team'),
        ),
        migrations.AddField(
            model_name='crawlresult',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.crawlrequest'),
        ),
    ]
