# Generated by Django 5.1.4 on 2025-01-14 15:58

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_crawlresultattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlresultattachment',
            name='attachment',
            field=models.FileField(max_length=511, upload_to=core.utils.generate_crawl_result_attachment_path, verbose_name='attachment'),
        ),
    ]
