# Generated by Django 5.1.4 on 2025-01-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_crawlresultattachment_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrequest',
            name='duration',
            field=models.DurationField(null=True, verbose_name='duration'),
        ),
    ]
