# Generated by Django 5.1.4 on 2025-03-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_crawlresult_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('running', 'Running'), ('finished', 'Finished'), ('cancelling', 'Canceling'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='new', max_length=255, verbose_name='status'),
        ),
    ]
