# Generated by Django 5.1.8 on 2025-04-16 21:23

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_crawlrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrequest',
            name='sitemap',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=core.utils.generate_crawl_request_sitemap_path, verbose_name='sitemap'),
        ),
    ]
