# Generated by Django 5.1.8 on 2025-04-25 12:18

import core.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_crawlrequest_sitemap'),
        ('user', '0012_teaminvitation_invitation_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(max_length=255, verbose_name='query')),
                ('search_options', models.JSONField(default=dict, verbose_name='search options')),
                ('result_limit', models.PositiveIntegerField(default=5, verbose_name='result limit')),
                ('duration', models.DurationField(null=True, verbose_name='duration')),
                ('status', models.CharField(choices=[('new', 'New'), ('running', 'Running'), ('finished', 'Finished'), ('cancelling', 'Canceling'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='new', max_length=255, verbose_name='status')),
                ('result', models.FileField(blank=True, max_length=255, null=True, upload_to=core.utils.search_result_file_path, verbose_name='result')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_requests', to='user.team', verbose_name='team')),
            ],
            options={
                'verbose_name': 'Search Request',
                'verbose_name_plural': 'Search Requests',
            },
        ),
    ]
