# Generated by Django 5.1.8 on 2025-05-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_proxyserver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxyserver',
            options={'ordering': ['team', 'name'], 'verbose_name': 'Proxy Server', 'verbose_name_plural': 'Proxy Servers'},
        ),
        migrations.AlterField(
            model_name='proxyserver',
            name='password',
            field=models.TextField(blank=True, null=True, verbose_name='password'),
        ),
    ]
