# Generated by Django 5.1.8 on 2025-05-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_proxyserver_options_alter_proxyserver_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyserver',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('premium', 'Premium'), ('team', 'Team')], default='general', max_length=255, verbose_name='proxy category'),
        ),
    ]
