# Generated by Django 5.2.1 on 2025-06-17 14:57

import core.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_proxyserver_category'),
        ('user', '0012_teaminvitation_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('running', 'Running'), ('finished', 'Finished'), ('canceling', 'Canceling'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='new', max_length=255, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='searchrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('running', 'Running'), ('finished', 'Finished'), ('canceling', 'Canceling'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='new', max_length=255, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='SitemapRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=255, verbose_name='url')),
                ('options', models.JSONField(default=dict, verbose_name='options')),
                ('status', models.CharField(choices=[('new', 'New'), ('running', 'Running'), ('finished', 'Finished'), ('canceling', 'Canceling'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='new', max_length=255, verbose_name='status')),
                ('duration', models.DurationField(null=True, verbose_name='duration')),
                ('result', models.FileField(blank=True, max_length=255, null=True, upload_to=core.utils.sitemap_result_file_path, verbose_name='result')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitemap_requests', to='user.team', verbose_name='team')),
            ],
            options={
                'verbose_name': 'Sitemap Request',
                'verbose_name_plural': 'Sitemap Requests',
            },
        ),
    ]
