# Generated by Django 5.2.1 on 2025-06-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0013_alter_crawlrequest_status_alter_searchrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrequest',
            name='urls',
            field=models.JSONField(default=list, verbose_name='urls'),
        ),
        migrations.RunSQL(
            "UPDATE core_crawlrequest SET urls = jsonb_build_array(to_jsonb(url)) WHERE urls IS NULL OR urls = '[]';",
            reverse_sql="UPDATE core_crawlrequest SET url = urls->>0 WHERE urls IS NOT NULL AND jsonb_array_length(urls) > 0;"
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE core_crawlrequest DROP COLUMN url;",
                    reverse_sql="ALTER TABLE core_crawlrequest ADD COLUMN url VARCHAR(255);"
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='crawlrequest',
                    name='url',
                ),
            ]
        ),
    ]
