# Generated by Django 5.2.1 on 2025-06-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_crawlrequest_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrequest',
            name='crawl_type',
            field=models.CharField(choices=[('single', 'Single'), ('batch', 'Batch')], default='single', max_length=255, verbose_name='crawl type'),
        ),
    ]
