name: Build and Push Docs Docker Image (Manual)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref (branch or tag) to build from. Leave blank for current.'
        required: false
        type: string

jobs:
  build-and-push-docs:
    name: Build and Push Docs Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.ref || github.ref }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set Environment Variables
        id: vars-docs
        run: |
          DATE=$(date +'%Y%m%d')
          if [[ ${{ github.ref }} == refs/heads/development ]]; then
            VERSION="alpha-${DATE}"
            echo "TAG=$VERSION" >> $GITHUB_ENV
            echo "DOCKER_TAGS=${{ secrets.DOCKER_USERNAME }}/docs:$VERSION,${{ secrets.DOCKER_USERNAME }}/docs:$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          elif [[ ${{ github.ref }} == refs/heads/main ]]; then
            VERSION="beta-${DATE}"
            echo "TAG=$VERSION" >> $GITHUB_ENV
            echo "DOCKER_TAGS=${{ secrets.DOCKER_USERNAME }}/docs:$VERSION,${{ secrets.DOCKER_USERNAME }}/docs:$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          elif [[ ${{ github.ref }} == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "TAG=$VERSION" >> $GITHUB_ENV
            echo "DOCKER_TAGS=${{ secrets.DOCKER_USERNAME }}/docs:$VERSION,${{ secrets.DOCKER_USERNAME }}/docs:$(git rev-parse --short HEAD),${{ secrets.DOCKER_USERNAME }}/docs:latest" >> $GITHUB_ENV
          else
            VERSION=$(git rev-parse --short HEAD)
            echo "TAG=$VERSION" >> $GITHUB_ENV
            echo "DOCKER_TAGS=${{ secrets.DOCKER_USERNAME }}/docs:$VERSION" >> $GITHUB_ENV
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./docs
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            APP_VERSION=${{ env.VERSION }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/docs:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/docs:buildcache,mode=max
          tags: ${{ env.DOCKER_TAGS }}
          labels: |
            org.opencontainers.image.created=${{ env.BUILD_DATE }}
            org.opencontainers.image.revision=${{ env.COMMIT_HASH }}
            org.opencontainers.image.version=${{ env.TAG }}
